name: CI

on:
    push:
        paths-ignore:
            - "docs/**"
            - "*.md"
    pull_request:
        paths-ignore:
            - "docs/**"
            - "*.md"

jobs:
    lint:
        name: Lint Code
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: actions/setup-node@v2.1.5
              with:
                  node-version: 14
            - name: Install
              run: npm install --ignore-scripts
            - name: Run Prettier
              run: npm run lint:prettier:ci

    commit-lint:
        name: Lint Commit Messages
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
              with:
                  fetch-depth: 0
            - uses: wagoid/commitlint-github-action@v3.0.1
              with:
                  configFile: ./package.json

    automerge:
        name: Automatically Merge Dependabot Pull Requests
        if: github.event.pull_request.draft == false
        needs: [commit-lint, lint]
        runs-on: ubuntu-latest
        steps:
            - uses: fastify/github-action-merge-dependabot@v2.0.0
              if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
